name: Gradle Updater

on:
  workflow_dispatch:
  schedule:
    # Every night at 5am
    - cron: "0 5 * * *"

jobs:
  upgrade-gradle-wrapper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update Gradle Wrapper
        uses: gradle-update/update-gradle-wrapper-action@v1
        with:
          repo-token: ${{ secrets.GH_PAT }}
