name: Publish on releases

on:
  release:
    types:
      - created

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11

      - name: Publish plugin to Gradle Portal
        uses: gradle/gradle-build-action@v2
        with:
          arguments: |
            publishPlugins
            -Pversion=${{ github.event.release.tag_name }}
            -Pgradle.publish.key=${{ secrets.GRADLE_API_KEY }}
            -Pgradle.publish.secret=${{ secrets.GRADLE_API_SECRET }}
