name: update-gradlew

on:
  workflow_dispatch:
  schedule:
    # Every night at 5am
    - cron: "0 5 * * *"

jobs:
  update-gradlew:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update Gradle wrapper
        uses: gradle-update/update-gradle-wrapper-action@v1
        with:
          repo-token: ${{ secrets.GH_PAT }}
